/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e_canteen;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Avadhoot
 */
public class Canteen2 extends javax.swing.JFrame {

    public class InsertDataFromTable {

    // Establish the database connection
    private Connection getConnection() throws SQLException {
        String url = "jdbc:mysql://localhost:3306/ecanteen?useSSL=false";
        String username = "root";
        String password = "@zgardi@n#1234";
        return DriverManager.getConnection(url, username, password);
    }

    // Insert data from JTable to the database
    public void insertDataFromTable(JTable table) {
    DefaultTableModel model = (DefaultTableModel) table.getModel();
    String query = "INSERT INTO canteen2 (username, item, quantity, price) VALUES (?, ?, ?, ?)";
    try (Connection connection = getConnection();
         PreparedStatement preparedStatement = connection.prepareStatement(query)) {
        for (int row = 0; row < model.getRowCount(); row++) {
            String username = jLabel19.getText(); // Assuming jLabel19 is a valid JLabel component that contains the username
            String item = (String) model.getValueAt(row, 0);
            String quantity = (String) model.getValueAt(row, 1);
            String price = (String) model.getValueAt(row, 2);
            preparedStatement.setString(1, username);
            preparedStatement.setString(2, item);
            preparedStatement.setString(3, quantity);
            preparedStatement.setString(4, price);
            preparedStatement.executeUpdate();
        }
        System.out.println("Data inserted successfully!");
    } catch (SQLException e) {
        System.err.println("Error: " + e.getMessage());
    }
    }
}
    
    
    /**
     * Creates new form Canteen2
     */
    public Canteen2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        maggip = new javax.swing.JLabel();
        coffeep = new javax.swing.JLabel();
        pizzap = new javax.swing.JLabel();
        browniep = new javax.swing.JLabel();
        frenchp = new javax.swing.JLabel();
        burgerp = new javax.swing.JLabel();
        frankyp = new javax.swing.JLabel();
        coldp = new javax.swing.JLabel();
        drinksp = new javax.swing.JLabel();
        greenp = new javax.swing.JLabel();
        pastap = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        coffee = new javax.swing.JComboBox<>();
        pizza = new javax.swing.JComboBox<>();
        brownie = new javax.swing.JComboBox<>();
        frenchfries = new javax.swing.JComboBox<>();
        burger = new javax.swing.JComboBox<>();
        franky = new javax.swing.JComboBox<>();
        coldcoffee = new javax.swing.JComboBox<>();
        maggi = new javax.swing.JComboBox<>();
        tea = new javax.swing.JComboBox<>();
        greentea = new javax.swing.JComboBox<>();
        colddrinks = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        coffeet = new javax.swing.JLabel();
        pizzat = new javax.swing.JLabel();
        browniet = new javax.swing.JLabel();
        frencht = new javax.swing.JLabel();
        burgert = new javax.swing.JLabel();
        frankyt = new javax.swing.JLabel();
        coldct = new javax.swing.JLabel();
        maggit = new javax.swing.JLabel();
        pastat = new javax.swing.JLabel();
        greent = new javax.swing.JLabel();
        colddt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totaltimerequired = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1070, 600));
        setMinimumSize(new java.awt.Dimension(1070, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1070, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 10, 90, 20);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 90));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CANTEEN 2");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(260, 40, 180, 30);

        jLabel10.setFont(new java.awt.Font("Algerian", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setText("E-Canteen ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(740, 10, 180, 40);

        jLabel19.setText("jLabel19");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(800, 70, 120, 16);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 920, 90));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 0, 38)); // NOI18N
        jLabel5.setText("MENU");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 110, 50));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/view edit delete product.png"))); // NOI18N
        jButton10.setText("ORDER");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 120, 30));

        maggip.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maggip.setText("70/-");
        getContentPane().add(maggip, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 30, 40));

        coffeep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coffeep.setText("10/-");
        getContentPane().add(coffeep, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 30, 40));

        pizzap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pizzap.setText("50/-");
        getContentPane().add(pizzap, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 30, 40));

        browniep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        browniep.setText("15/-");
        getContentPane().add(browniep, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 30, 40));

        frenchp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        frenchp.setText("15/-");
        getContentPane().add(frenchp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 30, 40));

        burgerp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        burgerp.setText("60/-");
        getContentPane().add(burgerp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 30, 40));

        frankyp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        frankyp.setText("100/-");
        getContentPane().add(frankyp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 40, 40));

        coldp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coldp.setText("70/-");
        getContentPane().add(coldp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 30, 40));

        drinksp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        drinksp.setText("10/-");
        getContentPane().add(drinksp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 30, 40));

        greenp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        greenp.setText("50/-");
        getContentPane().add(greenp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 30, 40));

        pastap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pastap.setText("15/-");
        getContentPane().add(pastap, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 30, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("PIZZA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("COFFEE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 90, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("BROWNIE");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("FRANKY");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 110, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("COLD COFFEE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 110, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("BURGER");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("FRENCH FRIES");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("MAGGI");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 100, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("COLD DRINKS");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("GREEN TEA");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 90, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("PASTA");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 100, -1));

        coffee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 0", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        coffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coffeeActionPerformed(evt);
            }
        });
        getContentPane().add(coffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 50, -1));

        pizza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 0", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaActionPerformed(evt);
            }
        });
        getContentPane().add(pizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 50, -1));

        brownie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 0", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        brownie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brownieActionPerformed(evt);
            }
        });
        getContentPane().add(brownie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 50, -1));

        frenchfries.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 0", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        frenchfries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frenchfriesActionPerformed(evt);
            }
        });
        getContentPane().add(frenchfries, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 50, -1));

        burger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 0", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        burger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgerActionPerformed(evt);
            }
        });
        getContentPane().add(burger, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 50, -1));

        franky.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 0", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        franky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frankyActionPerformed(evt);
            }
        });
        getContentPane().add(franky, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 50, -1));

        coldcoffee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 0", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        coldcoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coldcoffeeActionPerformed(evt);
            }
        });
        getContentPane().add(coldcoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 50, -1));

        maggi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 0", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        maggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maggiActionPerformed(evt);
            }
        });
        getContentPane().add(maggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 50, -1));

        tea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 0", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaActionPerformed(evt);
            }
        });
        getContentPane().add(tea, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 50, -1));

        greentea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 0", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        greentea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenteaActionPerformed(evt);
            }
        });
        getContentPane().add(greentea, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 50, -1));

        colddrinks.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " 0", " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9" }));
        colddrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colddrinksActionPerformed(evt);
            }
        });
        getContentPane().add(colddrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 50, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "QUANTITY", "PRICE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, 340));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("TOTAL :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 510, -1, -1));

        total.setText("TOTAL");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, -1, -1));

        jLabel6.setText("/- ONLY");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, -1, -1));

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        coffeet.setText(" 5");
        getContentPane().add(coffeet, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 164, 0, -1));

        pizzat.setText("10");
        getContentPane().add(pizzat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 204, 10, -1));

        browniet.setText("10");
        getContentPane().add(browniet, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 244, 10, -1));

        frencht.setText("5");
        getContentPane().add(frencht, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 284, 0, -1));

        burgert.setText("15");
        getContentPane().add(burgert, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 324, 10, -1));

        frankyt.setText("15");
        getContentPane().add(frankyt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 30, 20));

        coldct.setText("10");
        getContentPane().add(coldct, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 404, 10, -1));

        maggit.setText("15");
        getContentPane().add(maggit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 444, 10, -1));

        pastat.setText("17");
        getContentPane().add(pastat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 10, -1));

        greent.setText("15");
        getContentPane().add(greent, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 10, -1));

        colddt.setText("2");
        getContentPane().add(colddt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 10, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("TIME REQUIRED :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, 110, 20));

        totaltimerequired.setText("TIME");
        getContentPane().add(totaltimerequired, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 50, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("mins");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 540, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Dashboard DashboardFrame = new Dashboard();
        String txtUsername = jLabel9.getText();
        DashboardFrame.setVisible(true);
        DashboardFrame.pack();
        DashboardFrame.jLabel6.setText(txtUsername);
        DashboardFrame.setLocationRelativeTo(DashboardFrame);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
  String[] itemNames = {"Coffee", "Pizza", "Brownie", "French Fries", "Burger", "Franky", "Cold Coffee", "Maggi", "Cold Drinks", "Green Tea", "Tea"};
    JComboBox[] comboBoxes = {coffee, pizza, brownie, frenchfries, burger, franky, coldcoffee, maggi, colddrinks, greentea, tea};
    JLabel[] timelabels = {coffeet, pizzat, browniet, frencht, burgert, frankyt, coldct, maggit, colddt, greent, pastat};
    JLabel[] labels = {coffeep, pizzap, browniep, frenchp, burgerp, frankyp, coldp, maggip, drinksp, greenp, pastap};
    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Clearing the table before adding new rows
    model.setRowCount(0);
    int totalSum = 0;
    int totalTime = 0;

    for (int i = 0; i < 11; i++) { 
        String itemName = itemNames[i];
        String quantity = (String) comboBoxes[i].getSelectedItem();
        String price = labels[i].getText();
        String time = timelabels[i].getText();
        int quantityValue = Integer.parseInt(quantity.trim());
        int priceValue = Integer.parseInt(price.replace("/-", "").trim());
        int total = quantityValue * priceValue;
        int timeValue = Integer.parseInt(time.trim());

        if (quantityValue != 0) {
            model.addRow(new Object[]{itemName, quantity, price, total,timeValue});
            totalSum += total;
            totalTime += timeValue;
        }
    }
    String totalPrice = String.valueOf(totalSum);
    total.setText(totalPrice);
    String totaltime = String.valueOf(totalTime);
    totaltimerequired.setText(totaltime);
    
    }//GEN-LAST:event_jButton10ActionPerformed

    private void coffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coffeeActionPerformed

    private void pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pizzaActionPerformed

    private void brownieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brownieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brownieActionPerformed

    private void frenchfriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frenchfriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frenchfriesActionPerformed

    private void burgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_burgerActionPerformed

    private void frankyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frankyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frankyActionPerformed

    private void coldcoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coldcoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coldcoffeeActionPerformed

    private void maggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maggiActionPerformed

    private void teaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teaActionPerformed

    private void greenteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenteaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenteaActionPerformed

    private void colddrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colddrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colddrinksActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String txtUsername = jLabel19.getText();
        
        ConfirmOrder ConfirmOrderFrame = new ConfirmOrder(total.getText());
        ConfirmOrderFrame.setSource("Canteen1"); // or "Canteen2"
        ConfirmOrderFrame.setVisible(true);
        ConfirmOrderFrame.pack();
        ConfirmOrderFrame.jLabel3.setText(txtUsername);
        ConfirmOrderFrame.setLocationRelativeTo(ConfirmOrderFrame);
        this.dispose();
        
        Canteen2.InsertDataFromTable dataInserter = new Canteen2.InsertDataFromTable();
        dataInserter.insertDataFromTable(jTable1);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Canteen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Canteen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Canteen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Canteen2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Canteen2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brownie;
    private javax.swing.JLabel browniep;
    private javax.swing.JLabel browniet;
    private javax.swing.JComboBox<String> burger;
    private javax.swing.JLabel burgerp;
    private javax.swing.JLabel burgert;
    private javax.swing.JComboBox<String> coffee;
    private javax.swing.JLabel coffeep;
    private javax.swing.JLabel coffeet;
    private javax.swing.JComboBox<String> coldcoffee;
    private javax.swing.JLabel coldct;
    private javax.swing.JComboBox<String> colddrinks;
    private javax.swing.JLabel colddt;
    private javax.swing.JLabel coldp;
    private javax.swing.JLabel drinksp;
    private javax.swing.JComboBox<String> franky;
    private javax.swing.JLabel frankyp;
    private javax.swing.JLabel frankyt;
    private javax.swing.JComboBox<String> frenchfries;
    private javax.swing.JLabel frenchp;
    private javax.swing.JLabel frencht;
    private javax.swing.JLabel greenp;
    private javax.swing.JLabel greent;
    private javax.swing.JComboBox<String> greentea;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> maggi;
    private javax.swing.JLabel maggip;
    private javax.swing.JLabel maggit;
    private javax.swing.JLabel pastap;
    private javax.swing.JLabel pastat;
    private javax.swing.JComboBox<String> pizza;
    private javax.swing.JLabel pizzap;
    private javax.swing.JLabel pizzat;
    private javax.swing.JComboBox<String> tea;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totaltimerequired;
    // End of variables declaration//GEN-END:variables
}
