/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e_canteen;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;

/**
 *
 * @author Avadhoot
 */
public class ConfirmOrder1 extends javax.swing.JFrame {

private void sendToDatabase(String username, String totalValue) {
    try {
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecanteen?useSSL=false", "root", "@zgardi@n#1234");

        String query = "SELECT item FROM canteen2 WHERE username = ?";
        PreparedStatement itemStatement = connection.prepareStatement(query);
        itemStatement.setString(1, username);
        ResultSet itemResultSet = itemStatement.executeQuery();

        StringBuilder items = new StringBuilder();
        while (itemResultSet.next()) {
            items.append(itemResultSet.getString("item")).append(", ");
        }

        // Remove the trailing comma and whitespace
        if (items.length() > 2) {
            items.setLength(items.length() - 2);
        }

        String insertQuery = "INSERT INTO paycant2 (username, total, payment, item) VALUES (?, ?, ?, ?)";
        try (PreparedStatement insertStatement = connection.prepareStatement(insertQuery)) {
            insertStatement.setString(1, username);
            insertStatement.setString(2, totalValue);
            insertStatement.setString(3, "Payment Successful");
            insertStatement.setString(4, items.toString());
            insertStatement.executeUpdate();
        }

        JOptionPane.showMessageDialog(null, "Data inserted into the database successfully!");

        // Close the ResultSet and PreparedStatement
        itemResultSet.close();
        itemStatement.close();
        connection.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
}


    
    private String totalValue;

    public ConfirmOrder1(String total) {
        initComponents();
        this.totalValue = total;
        total2.setText(totalValue);
    }
      private String source;
    /**
     * Creates new form ConfirmOrder
     */
     public ConfirmOrder1() {
        initComponents();
    }
     
     public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 255));
        jLabel10.setText("E-Canteen ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(280, 30, 220, 48);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(150, 0, 930, 90);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 10, 90, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 150, 90);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("MAKE PAYMENT");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(110, 10, 150, 25);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ecanteen_logo (1).jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(100, 70, 160, 140);

        jLabel2.setFont(new java.awt.Font("Swis721 Ex BT", 0, 18)); // NOI18N
        jLabel2.setText(" Paying to Canteen 2");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(70, 210, 220, 50);

        total2.setFont(new java.awt.Font("Swis721 Ex BT", 0, 16)); // NOI18N
        total2.setText("Rs.");
        jPanel3.add(total2);
        total2.setBounds(130, 290, 60, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/verify users.png"))); // NOI18N
        jButton1.setText("Pay ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(120, 340, 120, 40);

        total.setFont(new java.awt.Font("Swis721 Ex BT", 0, 16)); // NOI18N
        total.setText("TOTAL");
        jPanel3.add(total);
        total.setBounds(170, 290, 60, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(180, 260, 120, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("FROM");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(120, 260, 70, 22);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(370, 110, 350, 430);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Canteen2 Canteen2Frame = new Canteen2();
        String txtUsername = jLabel3.getText();
        Canteen2Frame.setVisible(true);
        Canteen2Frame.pack();
        Canteen2Frame.jLabel19.setText(txtUsername);
        Canteen2Frame.setLocationRelativeTo(Canteen2Frame);
        this.dispose();
            if (source.equals("Canteen2")) {
            
        }
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
try {
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/ecanteen?useSSL=false", "root", "@zgardi@n#1234");
        String username = jLabel3.getText(); // Assuming jLabel3 contains the username
        sendToDatabase(username, totalValue); // Call the sendToDatabase method
        JOptionPane.showMessageDialog(null, "Payment Successful!");

        // Open the Dashboard frame
        ThankYou ThankYouFrame = new ThankYou();
        ThankYouFrame.setVisible(true);
        ThankYouFrame.pack();
        ThankYouFrame.jLabel2.setText(username);
        ThankYouFrame.setLocationRelativeTo(ThankYouFrame);
        this.dispose();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmOrder1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmOrder1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total2;
    // End of variables declaration//GEN-END:variables
}
