/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package e_canteen;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import doa.UserDao;
import doa.ConnectionProvider;


/**
 *
 * @author Avadhoot
 */
public class ForgotPassword extends javax.swing.JFrame {
 // Newly added field

    /**
     * Creates new form ForgotPassword
     */
 public ForgotPassword() {
        initComponents();
        btnUpdate.setEnabled(false);
        btnSearch.setEnabled(false);
        txtYourOTP.setEditable(false);
    }
    
    private String dbanswer = null;
    private String username = null;
    
    public void validateUsername() {
    String username = txtUsername.getText();
    if (!username.equals("")) {
        btnSearch.setEnabled(true);
    } else {
        btnSearch.setEnabled(false);
    }
}

    private void clear() {
    txtUsername.setText("");
    txtYourOTP.setText("");
    txtEnterNewPassword.setText("");
    txtYourOTP.setEditable(false);
    btnUpdate.setEnabled(false);
    btnSearch.setEnabled(false);
}

        public String getSecurityAnswer(String username) {
        
            Connection con = ConnectionProvider.getCon();
    try {
        PreparedStatement ps = con.prepareStatement("SELECT securityQuestion FROM user WHERE username=?");
        ps.setString(1, username);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            txtYourOTP.setText(rs.getString("securityQuestion")); 
            
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
    }
            
            
//            Connection con = ConnectionProvider.getCon();
//        try {
//            PreparedStatement ps = con.prepareStatement("SELECT answer FROM user WHERE username=?");
//            ps.setString(1, username);
//            ResultSet rs = ps.executeQuery();
//            if (rs.next()) {
//                return rs.getString("answer");
//            }
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, e);
//        }
        return null;
    }

    public boolean updatePassword(String username, String newPassword) {
        Connection con = ConnectionProvider.getCon();
        try {
            PreparedStatement ps = con.prepareStatement("UPDATE user SET password=? WHERE username=?");
            ps.setString(1, newPassword);
            ps.setString(2, username);
            int rowsAffected = ps.executeUpdate();
            return rowsAffected > 0;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtYourOTP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEnterNewPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtYourAnswer = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1070, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Forgot Your Password ?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 211, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 71, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Your Security Question");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 30));

        jLabel6.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 255));
        jLabel6.setText("E-Canteen");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 263, -1));

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 185, -1));

        txtYourOTP.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtYourOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYourOTPActionPerformed(evt);
            }
        });
        txtYourOTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtYourOTPKeyReleased(evt);
            }
        });
        getContentPane().add(txtYourOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 185, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/qiyrhywl (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 540, 600));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate);
        btnUpdate.setBounds(380, 450, 100, 27);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 153, 255));
        jButton5.setText("Login");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(230, 550, 80, 22);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch);
        btnSearch.setBounds(210, 450, 130, 27);

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 153, 255));
        jButton6.setText("Signup");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(110, 550, 80, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Get Back to                         or");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 540, 200, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Your Answer");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 340, 143, 30);

        txtEnterNewPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtEnterNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterNewPasswordActionPerformed(evt);
            }
        });
        txtEnterNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEnterNewPasswordKeyReleased(evt);
            }
        });
        jPanel2.add(txtEnterNewPassword);
        txtEnterNewPassword.setBounds(260, 390, 185, 28);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Enter New Password");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(60, 390, 143, 30);

        txtYourAnswer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtYourAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYourAnswerActionPerformed(evt);
            }
        });
        txtYourAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtYourAnswerKeyReleased(evt);
            }
        });
        jPanel2.add(txtYourAnswer);
        txtYourAnswer.setBounds(260, 340, 185, 28);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEnterNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterNewPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterNewPasswordActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login1().setVisible(true);
        dispose ();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        // TODO add your handling code here:
        validateUsername();
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void txtEnterNewPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEnterNewPasswordKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtEnterNewPasswordKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String answer = txtYourOTP.getText();
    String newPassword = new String(txtEnterNewPassword.getPassword());
    
    if (answer.equals(dbanswer)) {
        // If the answer matches the stored answer, update the password
        UserDao userDao = new UserDao(); // Assuming UserDao class exists to handle database operations
        boolean success = userDao.updatePassword(username, newPassword);
        if (success) {
            JOptionPane.showMessageDialog(this, "Password changed successfully!");
            clear(); // Clear the fields after successful password update
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update password. Please try again.");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Incorrect security answer. Please try again.");
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         String searchUsername = txtUsername.getText();
    UserDao userDao = new UserDao(); // Assuming UserDao class exists to handle database operations
    String securityQuestion = userDao.getSecurityQuestion(searchUsername);
    if (securityQuestion != null) {
        dbanswer = userDao.getSecurityAnswer(searchUsername); // Assuming method to fetch the security answer
        username = searchUsername; // Store the username for future use
        txtYourOTP.setEditable(true);
        txtYourOTP.requestFocus();
        btnSearch.setEnabled(false);
    } else {
        JOptionPane.showMessageDialog(this, "Username not found. Please try again.");
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Signup().setVisible(true);
        dispose ();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txtYourOTPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYourOTPKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtYourOTPKeyReleased

    private void txtYourOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYourOTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYourOTPActionPerformed

    private void txtYourAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYourAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYourAnswerActionPerformed

    private void txtYourAnswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYourAnswerKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYourAnswerKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtEnterNewPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtYourAnswer;
    private javax.swing.JTextField txtYourOTP;
    // End of variables declaration//GEN-END:variables

    private void validateFields() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
